# Generated by Django 5.1.4 on 2024-12-23 23:43

import user_upload.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ingestion_config',
            field=models.JSONField(decoder=user_upload.fields.IngestionConfigDecoder, default=user_upload.fields.IngestionConfig, encoder=user_upload.fields.IngestionConfigEncoder),
        ),
    ]
