# Generated by Django 5.1.7 on 2025-03-27 18:33

import agent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='capabilities',
            field=models.JSONField(default=list, validators=[agent.models.validate_capabilities]),
        ),
    ]
