# Generated by Django 5.1.7 on 2025-03-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agent_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='enable_vector_search',
            field=models.BooleanField(default=True, verbose_name='Memory Search'),
        ),
    ]
