# Generated by Django 5.1.7 on 2025-05-07 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_agent_enable_vector_search'),
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='llm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='llm.llm'),
        ),
    ]
