# Generated by Django 5.1.3 on 2024-11-23 18:07

from django.db import migrations, models

def create_admin(apps, schema_editor):
    from users.models import User, UserProfile
    
    # Create admin user
    admin = User.objects.create_user(
        username='admin',
        password='admin'
    )
    
    # Create admin profile
    user = UserProfile.objects.create(
        user=admin,
    )
    user.set_id
    user.set_as_superuser()

def reverse_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='admin').delete()

class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial")  # rimosso .py
    ]

    operations = [
        migrations.RunPython(create_admin, reverse_admin)
    ]
