# Generated by Django 5.1.7 on 2025-03-24 00:31

import file.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('file', models.JSONField(decoder=file.fields.FileObjectDecoder, encoder=file.fields.FileObjectEncoder)),
                ('file_id', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('hash', models.CharField(blank=True, null=True)),
                ('ingested', models.BooleanField(default=False)),
                ('ingestion_config', models.JSONField(decoder=file.fields.IngestionConfigDecoder, default=file.fields.IngestionConfig, encoder=file.fields.IngestionConfigEncoder)),
                ('status', models.CharField(choices=[('pending_config', 'Configuring'), ('pending_process', 'Post processing'), ('pending_upload', 'Uploading'), ('ready', 'Ready')], default='pending_config', max_length=20)),
                ('config_progress', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
            },
        ),
        migrations.CreateModel(
            name='FileLibraryAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'file library association',
                'verbose_name_plural': 'file library associations',
            },
        ),
    ]
