# Generated by Django 5.1.4 on 2024-12-18 12:12

import django.db.models.deletion
import file.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0002_alter_library_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('file', models.JSONField(decoder=file.fields.FileObjectDecoder, encoder=file.fields.FileObjectEncoder)),
                ('file_id', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('hash', models.CharField(blank=True, null=True)),
                ('ingested', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
            },
        ),
        migrations.CreateModel(
            name='FileLibraryAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='file.file')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='library.library')),
            ],
            options={
                'verbose_name': 'file library association',
                'verbose_name_plural': 'file library associations',
            },
        ),
    ]
