# Generated by Django 5.1.4 on 2024-12-23 23:43

import file.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ingestion_config',
            field=models.JSONField(decoder=file.fields.IngestionConfigDecoder, default=file.fields.IngestionConfig, encoder=file.fields.IngestionConfigEncoder),
        ),
    ]
