# Generated by Django 5.1.4 on 2024-12-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_file_config_progress_file_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('pending_config', 'In configurazione'), ('pending_process', 'Post processing'), ('pending_upload', 'In caricamento'), ('ready', 'Pronto')], default='pending_config', max_length=20),
        ),
    ]
