# Generated by Django 5.1.5 on 2025-02-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_alter_file_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('pending_config', 'Configuring'), ('pending_process', 'Post processing'), ('pending_upload', 'Uploading'), ('ready', 'Ready')], default='pending_config', max_length=20),
        ),
    ]
