# Generated by Django 5.1.7 on 2025-03-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='libraries',
            field=models.ManyToManyField(blank=True, related_name='chats', to='library.library'),
        ),
    ]
