# Generated by Django 5.1.4 on 2024-12-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_options_remove_message_user_and_more'),
        ('library', '0002_alter_library_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='libraries',
            field=models.ManyToManyField(blank=True, related_name='chats', to='library.library'),
        ),
    ]
