# Generated by Django 5.1.4 on 2025-01-05 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_options_chat_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-created_at'], 'verbose_name': 'chat', 'verbose_name_plural': 'chats'},
        ),
    ]
