# Generated by Django 5.1.5 on 2025-02-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(default='Nuova Chat', max_length=255),
        ),
    ]
