# Generated by Django 5.1.5 on 2025-02-19 23:19

import agent.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('chat', '0006_chat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='agent',
            field=models.ForeignKey(default=agent.models.Agent.get_default, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='agent.agent'),
        ),
    ]
