# Generated by Django 5.1.5 on 2025-02-19 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('chat', '0006_chat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='agent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='agent.agent'),
        ),
    ]
