# Generated by Django 5.1.5 on 2025-03-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='annotations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
