# Generated by Django 5.1.5 on 2025-03-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chat_title'),
        ('file', '0005_alter_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='messages', to='file.file'),
        ),
    ]
